[project]
name = "spinning-up-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["datasets", "huggingface_hub", "verifiers"]
